{{- if .Values.monitoring.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "kusama-monitor.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "kusama-monitor.name" . }}
  endpoints:
  - port: http
    path: /metrics
{{- end }}
