apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-kusama-monitor
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-kusama-monitor
  template:
    metadata:
      labels:
        app: my-kusama-monitor
    spec:
      containers:
        - name: my-kusama-monitor
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          envFrom:
            - configMapRef:
                name: my-kusama-monitor-env
