replicaCount: 1
image:
  repository: your-kusama-monitor-image
  pullPolicy: IfNotPresent
  tag: latest
service:
  type: ClusterIP
  port: 3000
env:
  KUSAMA_RPC_ENDPOINT: "wss://kusama-rpc.polkadot.io/"
